In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("project started successfully!")

project started successfully!

# 1. Import Dataset

In [3]:
df = pd.read_csv("../data/raw/amazon_sales_data_uncleaned.csv")

In [4]:
df

,Title,Rating,Number_of_reviews,bought_in_last_month,Current/discounted_price,Price_on_variant,Listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6 out of 5 stars,375,300+ bought in past month,89.68,basic variant price: 2.4GHz,$159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,"Delivery Mon, Sep 1",Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,21-08-2025 11:14
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3 out of 5 stars,"2,457",6K+ bought in past month,9.99,basic variant price: nan,$15.99,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Fri, Aug 29",NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,21-08-2025 11:14
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6 out of 5 stars,"3,044",2K+ bought in past month,314,basic variant price: nan,$349.00,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Mon, Sep 1",NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,21-08-2025 11:14
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6 out of 5 stars,"35,882",10K+ bought in past month,NaN,basic variant price: $162.24,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,/Apple-Cancellation-Transparency-Personalized-...,21-08-2025 11:14
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8 out of 5 stars,"28,988",10K+ bought in past month,NaN,basic variant price: $72.74,No Discount,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,/Apple-MX542LL-A-AirTag-Pack/dp/B0D54JZTHY/ref...,21-08-2025 11:14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42670,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0 out of 5 stars,1,100+ bought in past month,195.99,basic variant price: nan,No Discount,No Badge,Organic,No Coupon,NaN,"FREE delivery Thu, Sep 4Or fastest delivery Tu...",NaN,https://m.media-amazon.com/images/I/51KCB+egEs...,/Elgato-4K-Pro-Internal-Capture/dp/B0DLR3WQWR/...,30-08-2025 19:56
42671,"Arlo Essential Spotlight Camera, Wireless Secu...",4.2 out of 5 stars,20,200+ bought in past month,89.99,basic variant price: $25.00 off coupon applied,No Discount,No Badge,Organic,Save $25.00 with coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery Mo...",NaN,https://m.media-amazon.com/images/I/51jV+o1LZE...,/Arlo-Essential-Spotlight-Camera-Surveillance/...,30-08-2025 19:56
42672,"GIGABYTE - AORUS FO32U2-32"" QD OLED Gaming Mon...",4.3 out of 5 stars,57,50+ bought in past month,899.99,basic variant price: Lowest price in 30 days,"$1,099.99",Save 18%,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,https://m.media-amazon.com/images/I/71ySPkNLkG...,/GIGABYTE-FO32U2-32-3840x2160-240Hz-FreeSync-A...,30-08-2025 19:56
42673,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7 out of 5 stars,"7,102",500+ bought in past month,10.39,basic variant price: nan,$15.98,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4 on $35 of items shipp...",NaN,https://m.media-amazon.com/images/I/411c0JFJ79...,/Monoprice-XLR-Male-4-Inch-Cable/dp/B001UJEKZ6...,30-08-2025 19:56
42674,Lorex Fusion 1080p HD Security Camera System w...,4.4 out of 5 stars,75,50+ bought in past month,419.99,basic variant price: nan,$499.99,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,https://m.media-amazon.com/images/I/71wTn+zoSr...,/Lorex-8-Channel-Security-Outdoor-Cameras/dp/B...,30-08-2025 19:56

# 2. Understand the dataset

In [5]:
df.head()

,Title,Rating,Number_of_reviews,bought_in_last_month,Current/discounted_price,Price_on_variant,Listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6 out of 5 stars,375,300+ bought in past month,89.68,basic variant price: 2.4GHz,$159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,"Delivery Mon, Sep 1",Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,21-08-2025 11:14
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3 out of 5 stars,"2,457",6K+ bought in past month,9.99,basic variant price: nan,$15.99,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Fri, Aug 29",NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,21-08-2025 11:14
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6 out of 5 stars,"3,044",2K+ bought in past month,314,basic variant price: nan,$349.00,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Mon, Sep 1",NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,21-08-2025 11:14
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6 out of 5 stars,"35,882",10K+ bought in past month,NaN,basic variant price: $162.24,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,/Apple-Cancellation-Transparency-Personalized-...,21-08-2025 11:14
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8 out of 5 stars,"28,988",10K+ bought in past month,NaN,basic variant price: $72.74,No Discount,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,/Apple-MX542LL-A-AirTag-Pack/dp/B0D54JZTHY/ref...,21-08-2025 11:14

In [6]:
df.tail()

,Title,Rating,Number_of_reviews,bought_in_last_month,Current/discounted_price,Price_on_variant,Listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at
42670,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0 out of 5 stars,1,100+ bought in past month,195.99,basic variant price: nan,No Discount,No Badge,Organic,No Coupon,NaN,"FREE delivery Thu, Sep 4Or fastest delivery Tu...",NaN,https://m.media-amazon.com/images/I/51KCB+egEs...,/Elgato-4K-Pro-Internal-Capture/dp/B0DLR3WQWR/...,30-08-2025 19:56
42671,"Arlo Essential Spotlight Camera, Wireless Secu...",4.2 out of 5 stars,20,200+ bought in past month,89.99,basic variant price: $25.00 off coupon applied,No Discount,No Badge,Organic,Save $25.00 with coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery Mo...",NaN,https://m.media-amazon.com/images/I/51jV+o1LZE...,/Arlo-Essential-Spotlight-Camera-Surveillance/...,30-08-2025 19:56
42672,"GIGABYTE - AORUS FO32U2-32"" QD OLED Gaming Mon...",4.3 out of 5 stars,57,50+ bought in past month,899.99,basic variant price: Lowest price in 30 days,"$1,099.99",Save 18%,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,https://m.media-amazon.com/images/I/71ySPkNLkG...,/GIGABYTE-FO32U2-32-3840x2160-240Hz-FreeSync-A...,30-08-2025 19:56
42673,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7 out of 5 stars,"7,102",500+ bought in past month,10.39,basic variant price: nan,$15.98,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4 on $35 of items shipp...",NaN,https://m.media-amazon.com/images/I/411c0JFJ79...,/Monoprice-XLR-Male-4-Inch-Cable/dp/B001UJEKZ6...,30-08-2025 19:56
42674,Lorex Fusion 1080p HD Security Camera System w...,4.4 out of 5 stars,75,50+ bought in past month,419.99,basic variant price: nan,$499.99,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,https://m.media-amazon.com/images/I/71wTn+zoSr...,/Lorex-8-Channel-Security-Outdoor-Cameras/dp/B...,30-08-2025 19:56

In [7]:
df.shape

(42675, 16)

In [8]:
df.columns

Index(['Title', 'Rating', 'Number_of_reviews', 'bought_in_last_month',
       'Current/discounted_price', 'Price_on_variant', 'Listed_price',
       'is_best_seller', 'is_sponsored', 'is_couponed', 'buy_box_availability',
       'delivery_details', 'sustainability_badges', 'image_url', 'product_url',
       'collected_at'],
      dtype='object')

# 3.Check Datatypes

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Title                     42675 non-null  object
 1   Rating                    41651 non-null  object
 2   Number_of_reviews         41651 non-null  object
 3   bought_in_last_month      39458 non-null  object
 4   Current/discounted_price  30926 non-null  object
 5   Price_on_variant          42675 non-null  object
 6   Listed_price              42675 non-null  object
 7   is_best_seller            42675 non-null  object
 8   is_sponsored              42675 non-null  object
 9   is_couponed               42675 non-null  object
 10  buy_box_availability      28022 non-null  object
 11  delivery_details          30955 non-null  object
 12  sustainability_badges     3408 non-null   object
 13  image_url                 42675 non-null  object
 14  product_url               40606 non-null  object
 15  collected_at              42675 non-null  object
dtypes: object(16)
memory usage: 5.2+ MB

In [10]:
df.describe()

,Title,Rating,Number_of_reviews,bought_in_last_month,Current/discounted_price,Price_on_variant,Listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at
count,42675,41651,41651,39458,30926,42675,42675,42675,42675,42675,28022,30955,3408,42675,40606,42675
unique,8808,31,4413,59,2576,3466,911,12,2,42,1,298,16,8038,40606,331
top,"Duracell Coppertop 9V Battery, 6 Count (Pack o...",4.6 out of 5 stars,25,100+ bought in past month,29.99,basic variant price: nan,No Discount,No Badge,Organic,No Coupon,Add to cart,"Delivery Mon, Sep 1",Small Business,https://m.media-amazon.com/images/I/51Xr76m2WL...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,27-08-2025 07:39
freq,744,6151,626,8801,825,21031,30364,40814,35664,40727,28022,6189,1341,1461,1,180

# 4. Check Memory usage

In [11]:
df.memory_usage(deep=True)

Index                            132
Title                        8381538
Rating                       2823385
Number_of_reviews            2216846
bought_in_last_month         3090956
Current/discounted_price     2049247
Price_on_variant             3210717
Listed_price                 2504397
is_best_seller               2436870
is_sponsored                 2403822
is_couponed                  2501075
buy_box_availability         2150216
delivery_details             2762595
sustainability_badges        1476261
image_url                    4736925
product_url                 24849945
collected_at                 2773875
dtype: int64

In [16]:
df.memory_usage(deep=True).sum()/1024**2

np.float64(67.82679557800293)

In [13]:
df.isnull().sum()

Title                           0
Rating                       1024
Number_of_reviews            1024
bought_in_last_month         3217
Current/discounted_price    11749
Price_on_variant                0
Listed_price                    0
is_best_seller                  0
is_sponsored                    0
is_couponed                     0
buy_box_availability        14653
delivery_details            11720
sustainability_badges       39267
image_url                       0
product_url                  2069
collected_at                    0
dtype: int64

In [14]:
df.nunique()

Title                        8808
Rating                         31
Number_of_reviews            4413
bought_in_last_month           59
Current/discounted_price     2576
Price_on_variant             3466
Listed_price                  911
is_best_seller                 12
is_sponsored                    2
is_couponed                    42
buy_box_availability            1
delivery_details              298
sustainability_badges          16
image_url                    8038
product_url                 40606
collected_at                  331
dtype: int64

In [15]:
df[df["Current/discounted_price"].isnull()].head(10)

,Title,Rating,Number_of_reviews,bought_in_last_month,Current/discounted_price,Price_on_variant,Listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6 out of 5 stars,"35,882",10K+ bought in past month,NaN,basic variant price: $162.24,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,/Apple-Cancellation-Transparency-Personalized-...,21-08-2025 11:14
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8 out of 5 stars,"28,988",10K+ bought in past month,NaN,basic variant price: $72.74,No Discount,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,/Apple-MX542LL-A-AirTag-Pack/dp/B0D54JZTHY/ref...,21-08-2025 11:14
5,Texas Instruments TI-84 Plus CE Color Graphing...,4.6 out of 5 stars,"44,522",100K+ bought in past month,NaN,basic variant price: $99.95,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/71AyPChhFd...,/Texas-Instruments-TI-84-Graphing-Calculator/d...,21-08-2025 11:14
6,"Apple AirPods 4 Wireless Earbuds, Bluetooth He...",4.5 out of 5 stars,"13,466",10K+ bought in past month,NaN,basic variant price: $88.11,No Discount,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61iBtxCUab...,/Apple-Bluetooth-Headphones-Personalized-Effor...,21-08-2025 11:14
7,Apple AirTag. Keep Track of and find Your Keys...,4.6 out of 5 stars,"38,105",10K+ bought in past month,NaN,basic variant price: $23.04,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/71rP7f78eF...,/Apple-MX532LL-A-AirTag/dp/B0CWXNS552/ref=sr_1...,21-08-2025 11:14
9,"Apple iPad 11-inch: A16 chip, 11-inch Model, L...",4.7 out of 5 stars,"7,308",10K+ bought in past month,NaN,basic variant price: $284.05,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,Energy efficiency,https://m.media-amazon.com/images/I/61aPY8odPS...,/Apple-iPad-11-inch-Display-All-Day/dp/B0DZ75T...,21-08-2025 11:14
11,Apple 2025 MacBook Air 13-inch Laptop with M4 ...,4.8 out of 5 stars,"1,914",10K+ bought in past month,NaN,basic variant price: $880.95,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,Energy efficiency,https://m.media-amazon.com/images/I/71cWZUr9SV...,/Apple-2025-MacBook-13-inch-Laptop/dp/B0DZD9S5...,21-08-2025 11:14
15,Texas Instruments TI-30XIIS Scientific Calcula...,4.7 out of 5 stars,"48,468",100K+ bought in past month,NaN,basic variant price: $17.45,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/5198+fcBR+...,/Texas-Instruments-Scientific-Calculator-Accen...,21-08-2025 11:14
19,Roku Streaming Stick HD 2025 — HD Streaming De...,4.6 out of 5 stars,"1,909",10K+ bought in past month,NaN,basic variant price: $33.51,No Discount,No Badge,Organic,No Coupon,NaN,NaN,Works with Alexa,https://m.media-amazon.com/images/I/71mye7IQ5j...,/Roku-Streaming-Stick-HD-2025/dp/B0DXXYS4BJ/re...,21-08-2025 11:14
21,Apple Watch SE (2nd Gen) [GPS 40mm] Smartwatch...,4.6 out of 5 stars,"12,840",10K+ bought in past month,NaN,basic variant price: $146.14,No Discount,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61umEhyV-U...,/Apple-Smartwatch-Starlight-Aluminum-Detection...,21-08-2025 11:14

# 5. Data Cleaning

In [25]:
for col in df.columns:
    print("\n---", col, "---")
    print(df[col].dropna().unique()[:10])

--- Title ---
['BOYA BOYALINK 2 Wireless Lavalier Microphone for iPhone Camera Android, Mini Lapel Micophone Wireless, 48 KHz 24 Bit, 6mm Mic, 1000ft, 30h Use, Noise Cancelling, Clip on Mic USB-C/Lightning/3.5mm TRS'
 'LISEN USB C to Lightning Cable, 240W 4 in 1 Charging Cable 6.6FT, Chubby USB A/C to C/Lightning with Light for iPhone 16e 15 14 Pro/MacBook Air 17/iPad/Samsung/Switch 2, Multi Chargers for All Devices'
 'DJI Mic 2 (2 TX + 1 RX + Charging Case), Wireless Lavalier Microphone, Intelligent Noise Cancelling, 32-bit Float Internal Recording, 820 ft.(250m) Range, Microphone for iPhone, Android, Camera'
 'Apple AirPods Pro 2 Wireless Earbuds, Active Noise Cancellation, Hearing Aid Feature, Bluetooth Headphones, Transparency, Personalized Spatial Audio, High-Fidelity Sound, H2 Chip, USB-C Charging'
 'Apple AirTag 4 Pack. Keep Track of and find Your Keys, Wallet, Luggage, Backpack, and More. Simple one-tap Set up with iPhone or iPad'
 'Texas Instruments TI-84 Plus CE Color Graphing Calculator, Black'
 'Apple AirPods 4 Wireless Earbuds, Bluetooth Headphones, Personalized Spatial Audio, Sweat and Water Resistant, USB-C Charging Case, H2 Chip, Up to 30 Hours of Battery Life, Effortless Setup for iPhone'
 'Apple AirTag. Keep Track of and find Your Keys, Wallet, Luggage, Backpack, and More. Simple one-tap Set up with iPhone or iPad'
 'Complete Protect: One plan covers all eligible past and future purchases on Amazon'
 'Apple iPad 11-inch: A16 chip, 11-inch Model, Liquid Retina Display, 128GB, Wi-Fi 6, 12MP Front/12MP Back Camera, Touch ID, All-Day Battery Life — Blue']

--- Rating ---
['4.6 out of 5 stars' '4.3 out of 5 stars' '4.8 out of 5 stars'
 '4.5 out of 5 stars' '4.0 out of 5 stars' '4.7 out of 5 stars'
 '4.2 out of 5 stars' '4.4 out of 5 stars' '4.1 out of 5 stars'
 '4.9 out of 5 stars']

--- Number_of_reviews ---
['375' '2,457' '3,044' '35,882' '28,988' '44,522' '13,466' '38,105'
 '4,380' '7,308']

--- bought_in_last_month ---
['300+ bought in past month' '6K+ bought in past month'
 '2K+ bought in past month' '10K+ bought in past month'
 '100K+ bought in past month' '100+ bought in past month'
 '1K+ bought in past month' '500+ bought in past month'
 '80K+ bought in past month' '70K+ bought in past month']

--- Current/discounted_price ---
['89.68' '9.99' '314' '16.99' '14.99' '29.99' '249.99' '69.95' '39.97'
 '14.49']

--- Price_on_variant ---
['basic variant price: 2.4GHz' 'basic variant price: nan'
 'basic variant price: $162.24' 'basic variant price: $72.74'
 'basic variant price: $99.95' 'basic variant price: $88.11'
 'basic variant price: $23.04' 'basic variant price: $284.05'
 'basic variant price: $880.95' 'basic variant price: $17.45']

--- Listed_price ---
['$159.00' '$15.99' '$349.00' 'No Discount' '$19.98' '$14.33' '$17.99'
 '$21.89' '$20.00' '$48.99']

--- is_best_seller ---
['No Badge' 'Best Seller' "Amazon's" 'Limited time deal' 'Save 30%'
 'Save 12%' 'Save 9%' 'Save 17%' 'Save 77%' 'Ends in']

--- is_sponsored ---
['Sponsored' 'Organic']

--- is_couponed ---
['Save 15%  with coupon' 'No Coupon' 'Save 50%  with coupon'
 'Save $16.00  with coupon' 'Save $10.00  with coupon'
 'Save 10%  with coupon' 'Save $20.00  with coupon'
 'Save $4.00  with coupon' 'Save $0.33  with coupon'
 'Save $18.00  with coupon']

--- buy_box_availability ---
['Add to cart']

--- delivery_details ---
['Delivery Mon, Sep 1' 'Delivery Fri, Aug 29' 'Delivery Sep 1 - 11'
 'Delivery Sep 4 - 9' 'Delivery Sep 8 - 30' 'Delivery Aug 28 - Sep 1'
 'Delivery Sep 1 - 2' 'Delivery Aug 28 - Sep 3' 'Delivery Sep 1 - 9'
 'Delivery Aug 29 - Sep 2']

--- sustainability_badges ---
['Carbon impact' 'Energy efficiency' 'Safer chemicals +1 more'
 'Small Business' '1 sustainability certification' 'Works with Alexa'
 'Manufacturing practices' 'Forestry practices' 'Alexa Built-in'
 'Energy efficiency +3 more']

--- image_url ---
['https://m.media-amazon.com/images/I/71pAqiVEs3L._AC_UL320_.jpg'
 'https://m.media-amazon.com/images/I/61nbF6aVIPL._AC_UL320_.jpg'
 'https://m.media-amazon.com/images/I/61h78MEXojL._AC_UL320_.jpg'
 'https://m.media-amazon.com/images/I/61SUj2aKoEL._AC_UL320_.jpg'
 'https://m.media-amazon.com/images/I/61bMNCeAUAL._AC_UL320_.jpg'
 'https://m.media-amazon.com/images/I/71AyPChhFdL._AC_UL320_.jpg'
 'https://m.media-amazon.com/images/I/61iBtxCUabL._AC_UL320_.jpg'
 'https://m.media-amazon.com/images/I/71rP7f78eFL._AC_UL320_.jpg'
 'https://m.media-amazon.com/images/I/71tZ0n2xP9L._AC_UL320_.jpg'
 'https://m.media-amazon.com/images/I/61aPY8odPSL._AC_UL320_.jpg']

--- product_url ---
['/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxNDQ2OjE3NTU4MDAwNjg6c3BfYXRmX2Jyb3dzZTozMDA2NzE0NTMwMTcyMDI6OjA6Og&url=%2FBOYA-BOYALINK-Microphone-Micophone-Cancelling%2Fdp%2FB0DNZB7TQG%2Fref%3Dsr_1_1_sspa%3Fdib%3DeyJ2IjoiMSJ9.avmZlHCQuVOwikquBqYSIjN8SVcyxtkXHQMPt7Zjzkf4TeZzrZfQETMhdWuWgtTrVz8ITKpXLHvZj0fZRjxqgMPYNMitRqeUoeIwdYfc5nnzJ8m0T8HYeedlh3YSOhJQjeHskevMUQWyg6TtoB2tHcHt-edYPsQ6VwFQTI6avsPrgVpFKrto3ff9TDR9BcRyPwM6AiYn-vh7wA5PP9DjZddhCPf7bVPcHMZ6Hwd40dQDWm9_M8R-LcwKY8wnuWRUSplhfYJBvTjAgsb3Y3y88VGpfqY3V8Rd2ge-woBzUMA.yqwi-krmElGgXIMa8kKUPx1XmaXd9lHaAkMkVVpStxo%26dib_tag%3Dse%26qid%3D1755800068%26refinements%3Dp_n_g-101014971069111%253A119653281011%26s%3Delectronics%26sr%3D1-1-spons%26sp_csd%3Dd2lkZ2V0TmFtZT1zcF9hdGZfYnJvd3Nl%26psc%3D1'
 '/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxNDQ2OjE3NTU4MDAwNjg6c3BfYXRmX2Jyb3dzZTozMDA4NjA2Mzc2NDIxMDI6OjA6Og&url=%2FLISEN-Charging-Lighting-MacBook-Chargers%2Fdp%2FB0DHWZCZDZ%2Fref%3Dsr_1_2_sspa%3Fdib%3DeyJ2IjoiMSJ9.avmZlHCQuVOwikquBqYSIjN8SVcyxtkXHQMPt7Zjzkf4TeZzrZfQETMhdWuWgtTrVz8ITKpXLHvZj0fZRjxqgMPYNMitRqeUoeIwdYfc5nnzJ8m0T8HYeedlh3YSOhJQjeHskevMUQWyg6TtoB2tHcHt-edYPsQ6VwFQTI6avsPrgVpFKrto3ff9TDR9BcRyPwM6AiYn-vh7wA5PP9DjZddhCPf7bVPcHMZ6Hwd40dQDWm9_M8R-LcwKY8wnuWRUSplhfYJBvTjAgsb3Y3y88VGpfqY3V8Rd2ge-woBzUMA.yqwi-krmElGgXIMa8kKUPx1XmaXd9lHaAkMkVVpStxo%26dib_tag%3Dse%26qid%3D1755800068%26refinements%3Dp_n_g-101014971069111%253A119653281011%26s%3Delectronics%26sr%3D1-2-spons%26sp_csd%3Dd2lkZ2V0TmFtZT1zcF9hdGZfYnJvd3Nl%26psc%3D1'
 '/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxNDQ2OjE3NTU4MDAwNjg6c3BfYXRmX2Jyb3dzZTozMDA4Nzk0NzAxMTk3MDI6OjA6Og&url=%2FDJI-Microphone-Intelligent-Cancelling-Recording%2Fdp%2FB0CFZX734J%2Fref%3Dsr_1_3_sspa%3Fdib%3DeyJ2IjoiMSJ9.avmZlHCQuVOwikquBqYSIjN8SVcyxtkXHQMPt7Zjzkf4TeZzrZfQETMhdWuWgtTrVz8ITKpXLHvZj0fZRjxqgMPYNMitRqeUoeIwdYfc5nnzJ8m0T8HYeedlh3YSOhJQjeHskevMUQWyg6TtoB2tHcHt-edYPsQ6VwFQTI6avsPrgVpFKrto3ff9TDR9BcRyPwM6AiYn-vh7wA5PP9DjZddhCPf7bVPcHMZ6Hwd40dQDWm9_M8R-LcwKY8wnuWRUSplhfYJBvTjAgsb3Y3y88VGpfqY3V8Rd2ge-woBzUMA.yqwi-krmElGgXIMa8kKUPx1XmaXd9lHaAkMkVVpStxo%26dib_tag%3Dse%26qid%3D1755800068%26refinements%3Dp_n_g-101014971069111%253A119653281011%26s%3Delectronics%26sr%3D1-3-spons%26sp_csd%3Dd2lkZ2V0TmFtZT1zcF9hdGZfYnJvd3Nl%26psc%3D1'
 '/Apple-Cancellation-Transparency-Personalized-High-Fidelity/dp/B0D1XD1ZV3/ref=sr_1_4?dib=eyJ2IjoiMSJ9.avmZlHCQuVOwikquBqYSIjN8SVcyxtkXHQMPt7Zjzkf4TeZzrZfQETMhdWuWgtTrVz8ITKpXLHvZj0fZRjxqgMPYNMitRqeUoeIwdYfc5nnzJ8m0T8HYeedlh3YSOhJQjeHskevMUQWyg6TtoB2tHcHt-edYPsQ6VwFQTI6avsPrgVpFKrto3ff9TDR9BcRyPwM6AiYn-vh7wA5PP9DjZddhCPf7bVPcHMZ6Hwd40dQDWm9_M8R-LcwKY8wnuWRUSplhfYJBvTjAgsb3Y3y88VGpfqY3V8Rd2ge-woBzUMA.yqwi-krmElGgXIMa8kKUPx1XmaXd9lHaAkMkVVpStxo&dib_tag=se&qid=1755800068&refinements=p_n_g-101014971069111%3A119653281011&s=electronics&sr=1-4'
 '/Apple-MX542LL-A-AirTag-Pack/dp/B0D54JZTHY/ref=sr_1_5?dib=eyJ2IjoiMSJ9.avmZlHCQuVOwikquBqYSIjN8SVcyxtkXHQMPt7Zjzkf4TeZzrZfQETMhdWuWgtTrVz8ITKpXLHvZj0fZRjxqgMPYNMitRqeUoeIwdYfc5nnzJ8m0T8HYeedlh3YSOhJQjeHskevMUQWyg6TtoB2tHcHt-edYPsQ6VwFQTI6avsPrgVpFKrto3ff9TDR9BcRyPwM6AiYn-vh7wA5PP9DjZddhCPf7bVPcHMZ6Hwd40dQDWm9_M8R-LcwKY8wnuWRUSplhfYJBvTjAgsb3Y3y88VGpfqY3V8Rd2ge-woBzUMA.yqwi-krmElGgXIMa8kKUPx1XmaXd9lHaAkMkVVpStxo&dib_tag=se&qid=1755800068&refinements=p_n_g-101014971069111%3A119653281011&s=electronics&sr=1-5'
 '/Texas-Instruments-TI-84-Graphing-Calculator/dp/B00TFYYWQA/ref=sr_1_6?dib=eyJ2IjoiMSJ9.avmZlHCQuVOwikquBqYSIjN8SVcyxtkXHQMPt7Zjzkf4TeZzrZfQETMhdWuWgtTrVz8ITKpXLHvZj0fZRjxqgMPYNMitRqeUoeIwdYfc5nnzJ8m0T8HYeedlh3YSOhJQjeHskevMUQWyg6TtoB2tHcHt-edYPsQ6VwFQTI6avsPrgVpFKrto3ff9TDR9BcRyPwM6AiYn-vh7wA5PP9DjZddhCPf7bVPcHMZ6Hwd40dQDWm9_M8R-LcwKY8wnuWRUSplhfYJBvTjAgsb3Y3y88VGpfqY3V8Rd2ge-woBzUMA.yqwi-krmElGgXIMa8kKUPx1XmaXd9lHaAkMkVVpStxo&dib_tag=se&qid=1755800068&refinements=p_n_g-101014971069111%3A119653281011&s=electronics&sr=1-6'
 '/Apple-Bluetooth-Headphones-Personalized-Effortless/dp/B0DGHMNQ5Z/ref=sr_1_7?dib=eyJ2IjoiMSJ9.avmZlHCQuVOwikquBqYSIjN8SVcyxtkXHQMPt7Zjzkf4TeZzrZfQETMhdWuWgtTrVz8ITKpXLHvZj0fZRjxqgMPYNMitRqeUoeIwdYfc5nnzJ8m0T8HYeedlh3YSOhJQjeHskevMUQWyg6TtoB2tHcHt-edYPsQ6VwFQTI6avsPrgVpFKrto3ff9TDR9BcRyPwM6AiYn-vh7wA5PP9DjZddhCPf7bVPcHMZ6Hwd40dQDWm9_M8R-LcwKY8wnuWRUSplhfYJBvTjAgsb3Y3y88VGpfqY3V8Rd2ge-woBzUMA.yqwi-krmElGgXIMa8kKUPx1XmaXd9lHaAkMkVVpStxo&dib_tag=se&qid=1755800068&refinements=p_n_g-101014971069111%3A119653281011&s=electronics&sr=1-7'
 '/Apple-MX532LL-A-AirTag/dp/B0CWXNS552/ref=sr_1_8?dib=eyJ2IjoiMSJ9.avmZlHCQuVOwikquBqYSIjN8SVcyxtkXHQMPt7Zjzkf4TeZzrZfQETMhdWuWgtTrVz8ITKpXLHvZj0fZRjxqgMPYNMitRqeUoeIwdYfc5nnzJ8m0T8HYeedlh3YSOhJQjeHskevMUQWyg6TtoB2tHcHt-edYPsQ6VwFQTI6avsPrgVpFKrto3ff9TDR9BcRyPwM6AiYn-vh7wA5PP9DjZddhCPf7bVPcHMZ6Hwd40dQDWm9_M8R-LcwKY8wnuWRUSplhfYJBvTjAgsb3Y3y88VGpfqY3V8Rd2ge-woBzUMA.yqwi-krmElGgXIMa8kKUPx1XmaXd9lHaAkMkVVpStxo&dib_tag=se&qid=1755800068&refinements=p_n_g-101014971069111%3A119653281011&s=electronics&sr=1-8'
 '/Asurion-Complete-Protect/dp/B07RZ3LSHM/ref=sr_1_9?dib=eyJ2IjoiMSJ9.avmZlHCQuVOwikquBqYSIjN8SVcyxtkXHQMPt7Zjzkf4TeZzrZfQETMhdWuWgtTrVz8ITKpXLHvZj0fZRjxqgMPYNMitRqeUoeIwdYfc5nnzJ8m0T8HYeedlh3YSOhJQjeHskevMUQWyg6TtoB2tHcHt-edYPsQ6VwFQTI6avsPrgVpFKrto3ff9TDR9BcRyPwM6AiYn-vh7wA5PP9DjZddhCPf7bVPcHMZ6Hwd40dQDWm9_M8R-LcwKY8wnuWRUSplhfYJBvTjAgsb3Y3y88VGpfqY3V8Rd2ge-woBzUMA.yqwi-krmElGgXIMa8kKUPx1XmaXd9lHaAkMkVVpStxo&dib_tag=se&qid=1755800068&refinements=p_n_g-101014971069111%3A119653281011&s=electronics&sr=1-9'
 '/Apple-iPad-11-inch-Display-All-Day/dp/B0DZ75TN5F/ref=sr_1_10?dib=eyJ2IjoiMSJ9.avmZlHCQuVOwikquBqYSIjN8SVcyxtkXHQMPt7Zjzkf4TeZzrZfQETMhdWuWgtTrVz8ITKpXLHvZj0fZRjxqgMPYNMitRqeUoeIwdYfc5nnzJ8m0T8HYeedlh3YSOhJQjeHskevMUQWyg6TtoB2tHcHt-edYPsQ6VwFQTI6avsPrgVpFKrto3ff9TDR9BcRyPwM6AiYn-vh7wA5PP9DjZddhCPf7bVPcHMZ6Hwd40dQDWm9_M8R-LcwKY8wnuWRUSplhfYJBvTjAgsb3Y3y88VGpfqY3V8Rd2ge-woBzUMA.yqwi-krmElGgXIMa8kKUPx1XmaXd9lHaAkMkVVpStxo&dib_tag=se&qid=1755800068&refinements=p_n_g-101014971069111%3A119653281011&s=electronics&sr=1-10']

--- collected_at ---
['21-08-2025 11:14' '21-08-2025 11:15' '21-08-2025 11:16'
 '21-08-2025 11:17' '21-08-2025 11:18' '21-08-2025 11:19'
 '21-08-2025 11:20' '21-08-2025 11:21' '21-08-2025 11:22'
 '21-08-2025 11:23']

In [26]:
df[['Rating',
    'Number_of_reviews',
    'bought_in_last_month',
    'Current/discounted_price',
    'Price_on_variant',
    'Listed_price',
    'is_best_seller',
    'is_sponsored',
    'is_couponed',
    'buy_box_availability'
]].head(10)

,Rating,Number_of_reviews,bought_in_last_month,Current/discounted_price,Price_on_variant,Listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability
0,4.6 out of 5 stars,375,300+ bought in past month,89.68,basic variant price: 2.4GHz,$159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart
1,4.3 out of 5 stars,"2,457",6K+ bought in past month,9.99,basic variant price: nan,$15.99,No Badge,Sponsored,No Coupon,Add to cart
2,4.6 out of 5 stars,"3,044",2K+ bought in past month,314,basic variant price: nan,$349.00,No Badge,Sponsored,No Coupon,Add to cart
3,4.6 out of 5 stars,"35,882",10K+ bought in past month,NaN,basic variant price: $162.24,No Discount,Best Seller,Organic,No Coupon,NaN
4,4.8 out of 5 stars,"28,988",10K+ bought in past month,NaN,basic variant price: $72.74,No Discount,No Badge,Organic,No Coupon,NaN
5,4.6 out of 5 stars,"44,522",100K+ bought in past month,NaN,basic variant price: $99.95,No Discount,Best Seller,Organic,No Coupon,NaN
6,4.5 out of 5 stars,"13,466",10K+ bought in past month,NaN,basic variant price: $88.11,No Discount,No Badge,Organic,No Coupon,NaN
7,4.6 out of 5 stars,"38,105",10K+ bought in past month,NaN,basic variant price: $23.04,No Discount,Best Seller,Organic,No Coupon,NaN
8,4.0 out of 5 stars,"4,380",NaN,16.99,basic variant price: nan,No Discount,No Badge,Organic,Save 50% with coupon,NaN
9,4.7 out of 5 stars,"7,308",10K+ bought in past month,NaN,basic variant price: $284.05,No Discount,Best Seller,Organic,No Coupon,NaN

In [27]:
df[['Rating',
    'Number_of_reviews',
    'bought_in_last_month',
    'Current/discounted_price',
    'Price_on_variant',
    'Listed_price'
]].sample(10)

,Rating,Number_of_reviews,bought_in_last_month,Current/discounted_price,Price_on_variant,Listed_price
7015,4.3 out of 5 stars,"1,113",200+ bought in past month,89.99,basic variant price: nan,$94.95
5817,4.7 out of 5 stars,162,600+ bought in past month,NaN,basic variant price: $54.99,No Discount
15798,4.5 out of 5 stars,"30,402",ESRB Rating: Everyone,68.99,basic variant price: nan,No Discount
4084,4.6 out of 5 stars,"14,096",1K+ bought in past month,12.96,basic variant price: $11.56,$20.26
707,4.7 out of 5 stars,"27,683",5K+ bought in past month,NaN,basic variant price: $40.89,No Discount
18711,NaN,NaN,NaN,59.99,basic variant price: nan,No Discount
4024,4.7 out of 5 stars,"3,15,834",1K+ bought in past month,14.35,basic variant price: $13.82,No Discount
31736,4.7 out of 5 stars,30,100+ bought in past month,77,basic variant price: $75.85,No Discount
30952,NaN,NaN,NaN,791.36,basic variant price: nan,No Discount
39178,4.7 out of 5 stars,386,200+ bought in past month,32.99,basic variant price: $31.96,No Discount

In [30]:
df["bought_in_last_month"].value_counts(dropna=False)

bought_in_last_month
100+ bought in past month                                                                                                                                                       8801
50+ bought in past month                                                                                                                                                        5967
200+ bought in past month                                                                                                                                                       5645
No featured offers available                                                                                                                                                    4571
NaN                                                                                                                                                                             3217
300+ bought in past month                                                                                                                                                       2842
500+ bought in past month                                                                                                                                                       2351
1K+ bought in past month                                                                                                                                                        2084
400+ bought in past month                                                                                                                                                       1436
20K+ bought in past month                                                                                                                                                        772
More Buying Choices                                                                                                                                                              654
Typical:                                                                                                                                                                         532
List:                                                                                                                                                                            518
List Price:                                                                                                                                                                      511
2K+ bought in past month                                                                                                                                                         426
800+ bought in past month                                                                                                                                                        280
Shop products from small business brands sold in Amazon’s store. Discover more about the small businesses partnering with Amazon and Amazon’s commitment to empowering them.     262
3K+ bought in past month                                                                                                                                                         249
600+ bought in past month                                                                                                                                                        229
10K+ bought in past month                                                                                                                                                        229
4K+ bought in past month                                                                                                                                                         196
5K+ bought in past month                                                                                                                                                         120
ESRB Rating: Everyone                                                                                                                                                            107
700+ bought in past month                                                                                                                                                        102
90K+ bought in past month                                                                                                                                                         92
6K+ bought in past month                                                                                                                                                          81
900+ bought in past month                                                                                                                                                         63
7K+ bought in past month                                                                                                                                                          49
This product is certified by Amazon to work with Alexa. This product can be controlled with your voice through Alexa-enabled devices such as Amazon Echo and Amazon Tap.          47
9K+ bought in past month                                                                                                                                                          44
8K+ bought in past month                                                                                                                                                          36
($766.33$766.33/in)                                                                                                                                                               29
30K+ bought in past month                                                                                                                                                         28
40K+ bought in past month                                                                                                                                                         14
($30.00$30.00/count)                                                                                                                                                              14
100K+ bought in past month                                                                                                                                                        13
Was:                                                                                                                                                                              10
($43.69$43.69/oz)                                                                                                                                                                  8
ESRB Rating: Rating Pending                                                                                                                                                        8
50K+ bought in past month                                                                                                                                                          6
70K+ bought in past month                                                                                                                                                          4
Alexa Built-in devices let you talk directly to Alexa, allowing you to play music, control your smart home, get news, weather, and more using your voice.                          3
60K+ bought in past month                                                                                                                                                          3
($1,999.75$1,999.75/100 cm)                                                                                                                                                        2
($53.33$53.33/count)                                                                                                                                                               2
($2.18$2.18/count)                                                                                                                                                                 2
($252.00$252.00/count)                                                                                                                                                             2
80K+ bought in past month                                                                                                                                                          2
($179.99$179.99/count)                                                                                                                                                             1
($5.27$5.27/in)                                                                                                                                                                    1
($1,080.00$1,080.00/kg)                                                                                                                                                            1
($828.56$828.56/kg)                                                                                                                                                                1
($46.81$46.81/oz)                                                                                                                                                                  1
($433.33$433.33/count)                                                                                                                                                             1
($4,813.00$4,813.00/100 cm)                                                                                                                                                        1
New Price:                                                                                                                                                                         1
($54.26$54.26/count)                                                                                                                                                               1
ESRB Rating: Adults Only                                                                                                                                                           1
ESRB Rating: Everyone 10+                                                                                                                                                          1
($1,315.78$1,315.78/kg)                                                                                                                                                            1
Name: count, dtype: int64

In [36]:
df["bought_in_last_month"].dropna().str.contains("bought in past month").value_counts()

bought_in_last_month
True     32164
False     7294
Name: count, dtype: int64

In [34]:
df.loc[
    ~df["bought_in_last_month"].fillna("").str.contains("bought in past month"),
    "bought_in_last_month"
].value_counts()

bought_in_last_month
No featured offers available                                                                                                                                                    4571
More Buying Choices                                                                                                                                                              654
Typical:                                                                                                                                                                         532
List:                                                                                                                                                                            518
List Price:                                                                                                                                                                      511
Shop products from small business brands sold in Amazon’s store. Discover more about the small businesses partnering with Amazon and Amazon’s commitment to empowering them.     262
ESRB Rating: Everyone                                                                                                                                                            107
This product is certified by Amazon to work with Alexa. This product can be controlled with your voice through Alexa-enabled devices such as Amazon Echo and Amazon Tap.          47
($766.33$766.33/in)                                                                                                                                                               29
($30.00$30.00/count)                                                                                                                                                              14
Was:                                                                                                                                                                              10
($43.69$43.69/oz)                                                                                                                                                                  8
ESRB Rating: Rating Pending                                                                                                                                                        8
Alexa Built-in devices let you talk directly to Alexa, allowing you to play music, control your smart home, get news, weather, and more using your voice.                          3
($2.18$2.18/count)                                                                                                                                                                 2
($252.00$252.00/count)                                                                                                                                                             2
($1,999.75$1,999.75/100 cm)                                                                                                                                                        2
($53.33$53.33/count)                                                                                                                                                               2
($828.56$828.56/kg)                                                                                                                                                                1
($179.99$179.99/count)                                                                                                                                                             1
($5.27$5.27/in)                                                                                                                                                                    1
ESRB Rating: Adults Only                                                                                                                                                           1
($54.26$54.26/count)                                                                                                                                                               1
($1,080.00$1,080.00/kg)                                                                                                                                                            1
($433.33$433.33/count)                                                                                                                                                             1
($4,813.00$4,813.00/100 cm)                                                                                                                                                        1
ESRB Rating: Everyone 10+                                                                                                                                                          1
($1,315.78$1,315.78/kg)                                                                                                                                                            1
New Price:                                                                                                                                                                         1
($46.81$46.81/oz)                                                                                                                                                                  1
Name: count, dtype: int64

In [37]:
df["estimated_monthly_purchases"] = (
    df["bought_in_last_month"]
    .where(
        df["bought_in_last_month"]
        .fillna("")
        .str.contains("bought in past month")
    )
)

In [38]:
df

,Title,Rating,Number_of_reviews,bought_in_last_month,Current/discounted_price,Price_on_variant,Listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at,estimated_monthly_purchases
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6 out of 5 stars,375,300+ bought in past month,89.68,basic variant price: 2.4GHz,$159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,"Delivery Mon, Sep 1",Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,21-08-2025 11:14,300+ bought in past month
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3 out of 5 stars,"2,457",6K+ bought in past month,9.99,basic variant price: nan,$15.99,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Fri, Aug 29",NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,21-08-2025 11:14,6K+ bought in past month
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6 out of 5 stars,"3,044",2K+ bought in past month,314,basic variant price: nan,$349.00,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Mon, Sep 1",NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,21-08-2025 11:14,2K+ bought in past month
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6 out of 5 stars,"35,882",10K+ bought in past month,NaN,basic variant price: $162.24,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,/Apple-Cancellation-Transparency-Personalized-...,21-08-2025 11:14,10K+ bought in past month
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8 out of 5 stars,"28,988",10K+ bought in past month,NaN,basic variant price: $72.74,No Discount,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,/Apple-MX542LL-A-AirTag-Pack/dp/B0D54JZTHY/ref...,21-08-2025 11:14,10K+ bought in past month
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42670,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0 out of 5 stars,1,100+ bought in past month,195.99,basic variant price: nan,No Discount,No Badge,Organic,No Coupon,NaN,"FREE delivery Thu, Sep 4Or fastest delivery Tu...",NaN,https://m.media-amazon.com/images/I/51KCB+egEs...,/Elgato-4K-Pro-Internal-Capture/dp/B0DLR3WQWR/...,30-08-2025 19:56,100+ bought in past month
42671,"Arlo Essential Spotlight Camera, Wireless Secu...",4.2 out of 5 stars,20,200+ bought in past month,89.99,basic variant price: $25.00 off coupon applied,No Discount,No Badge,Organic,Save $25.00 with coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery Mo...",NaN,https://m.media-amazon.com/images/I/51jV+o1LZE...,/Arlo-Essential-Spotlight-Camera-Surveillance/...,30-08-2025 19:56,200+ bought in past month
42672,"GIGABYTE - AORUS FO32U2-32"" QD OLED Gaming Mon...",4.3 out of 5 stars,57,50+ bought in past month,899.99,basic variant price: Lowest price in 30 days,"$1,099.99",Save 18%,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,https://m.media-amazon.com/images/I/71ySPkNLkG...,/GIGABYTE-FO32U2-32-3840x2160-240Hz-FreeSync-A...,30-08-2025 19:56,50+ bought in past month
42673,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7 out of 5 stars,"7,102",500+ bought in past month,10.39,basic variant price: nan,$15.98,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4 on $35 of items shipp...",NaN,https://m.media-amazon.com/images/I/411c0JFJ79...,/Monoprice-XLR-Male-4-Inch-Cable/dp/B001UJEKZ6...,30-08-2025 19:56,500+ bought in past month
42674,Lorex Fusion 1080p HD Security Camera System w...,4.4 out of 5 stars,75,50+ bought in past month,419.99,basic variant price: nan,$499.99,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,https://m.media-amazon.com/images/I/71wTn+zoSr...,/Lorex-8-Channel-Security-Outdoor-Cameras/dp/B...,30-08-2025 19:56,50+ bought in past month

In [46]:
extracted = df["estimated_monthly_purchases"].str.extract(
    r'(\d+(?:\.\d+)?)([Kk]?)',
    expand=True
)

extracted.columns = ["number", "unit"]

In [47]:
extracted

      number unit
0        300
1          6    K
2          2    K
3         10    K
4         10    K
...      ...  ...
42670    100
42671    200
42672     50
42673    500
42674     50

[42675 rows x 2 columns]

In [48]:
df["estimated_monthly_purchases"] = (
    pd.to_numeric(extracted["number"]) *
    extracted["unit"].str.lower().map({"k": 1000}).fillna(1)
)

In [49]:
df

,Title,Rating,Number_of_reviews,bought_in_last_month,Current/discounted_price,Price_on_variant,Listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at,estimated_monthly_purchases
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6 out of 5 stars,375,300+ bought in past month,89.68,basic variant price: 2.4GHz,$159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,"Delivery Mon, Sep 1",Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,21-08-2025 11:14,300.0
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3 out of 5 stars,"2,457",6K+ bought in past month,9.99,basic variant price: nan,$15.99,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Fri, Aug 29",NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,21-08-2025 11:14,6000.0
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6 out of 5 stars,"3,044",2K+ bought in past month,314,basic variant price: nan,$349.00,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Mon, Sep 1",NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,21-08-2025 11:14,2000.0
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6 out of 5 stars,"35,882",10K+ bought in past month,NaN,basic variant price: $162.24,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,/Apple-Cancellation-Transparency-Personalized-...,21-08-2025 11:14,10000.0
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8 out of 5 stars,"28,988",10K+ bought in past month,NaN,basic variant price: $72.74,No Discount,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,/Apple-MX542LL-A-AirTag-Pack/dp/B0D54JZTHY/ref...,21-08-2025 11:14,10000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42670,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0 out of 5 stars,1,100+ bought in past month,195.99,basic variant price: nan,No Discount,No Badge,Organic,No Coupon,NaN,"FREE delivery Thu, Sep 4Or fastest delivery Tu...",NaN,https://m.media-amazon.com/images/I/51KCB+egEs...,/Elgato-4K-Pro-Internal-Capture/dp/B0DLR3WQWR/...,30-08-2025 19:56,100.0
42671,"Arlo Essential Spotlight Camera, Wireless Secu...",4.2 out of 5 stars,20,200+ bought in past month,89.99,basic variant price: $25.00 off coupon applied,No Discount,No Badge,Organic,Save $25.00 with coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery Mo...",NaN,https://m.media-amazon.com/images/I/51jV+o1LZE...,/Arlo-Essential-Spotlight-Camera-Surveillance/...,30-08-2025 19:56,200.0
42672,"GIGABYTE - AORUS FO32U2-32"" QD OLED Gaming Mon...",4.3 out of 5 stars,57,50+ bought in past month,899.99,basic variant price: Lowest price in 30 days,"$1,099.99",Save 18%,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,https://m.media-amazon.com/images/I/71ySPkNLkG...,/GIGABYTE-FO32U2-32-3840x2160-240Hz-FreeSync-A...,30-08-2025 19:56,50.0
42673,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7 out of 5 stars,"7,102",500+ bought in past month,10.39,basic variant price: nan,$15.98,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4 on $35 of items shipp...",NaN,https://m.media-amazon.com/images/I/411c0JFJ79...,/Monoprice-XLR-Male-4-Inch-Cable/dp/B001UJEKZ6...,30-08-2025 19:56,500.0
42674,Lorex Fusion 1080p HD Security Camera System w...,4.4 out of 5 stars,75,50+ bought in past month,419.99,basic variant price: nan,$499.99,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,https://m.media-amazon.com/images/I/71wTn+zoSr...,/Lorex-8-Channel-Security-Outdoor-Cameras/dp/B...,30-08-2025 19:56,50.0