# Data Cleaning

In [21]:
import pandas as pd
import numpy as np

df = pd.read_csv("../Data/Raw/amazon_sales_data_uncleaned.csv")

In [22]:
df

,Title,Rating,Number_of_reviews,bought_in_last_month,Current/discounted_price,Price_on_variant,Listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6 out of 5 stars,375,300+ bought in past month,89.68,basic variant price: 2.4GHz,$159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,"Delivery Mon, Sep 1",Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,21-08-2025 11:14
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3 out of 5 stars,"2,457",6K+ bought in past month,9.99,basic variant price: nan,$15.99,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Fri, Aug 29",NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,21-08-2025 11:14
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6 out of 5 stars,"3,044",2K+ bought in past month,314,basic variant price: nan,$349.00,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Mon, Sep 1",NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,21-08-2025 11:14
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6 out of 5 stars,"35,882",10K+ bought in past month,NaN,basic variant price: $162.24,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,/Apple-Cancellation-Transparency-Personalized-...,21-08-2025 11:14
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8 out of 5 stars,"28,988",10K+ bought in past month,NaN,basic variant price: $72.74,No Discount,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,/Apple-MX542LL-A-AirTag-Pack/dp/B0D54JZTHY/ref...,21-08-2025 11:14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42670,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0 out of 5 stars,1,100+ bought in past month,195.99,basic variant price: nan,No Discount,No Badge,Organic,No Coupon,NaN,"FREE delivery Thu, Sep 4Or fastest delivery Tu...",NaN,https://m.media-amazon.com/images/I/51KCB+egEs...,/Elgato-4K-Pro-Internal-Capture/dp/B0DLR3WQWR/...,30-08-2025 19:56
42671,"Arlo Essential Spotlight Camera, Wireless Secu...",4.2 out of 5 stars,20,200+ bought in past month,89.99,basic variant price: $25.00 off coupon applied,No Discount,No Badge,Organic,Save $25.00 with coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery Mo...",NaN,https://m.media-amazon.com/images/I/51jV+o1LZE...,/Arlo-Essential-Spotlight-Camera-Surveillance/...,30-08-2025 19:56
42672,"GIGABYTE - AORUS FO32U2-32"" QD OLED Gaming Mon...",4.3 out of 5 stars,57,50+ bought in past month,899.99,basic variant price: Lowest price in 30 days,"$1,099.99",Save 18%,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,https://m.media-amazon.com/images/I/71ySPkNLkG...,/GIGABYTE-FO32U2-32-3840x2160-240Hz-FreeSync-A...,30-08-2025 19:56
42673,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7 out of 5 stars,"7,102",500+ bought in past month,10.39,basic variant price: nan,$15.98,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4 on $35 of items shipp...",NaN,https://m.media-amazon.com/images/I/411c0JFJ79...,/Monoprice-XLR-Male-4-Inch-Cable/dp/B001UJEKZ6...,30-08-2025 19:56
42674,Lorex Fusion 1080p HD Security Camera System w...,4.4 out of 5 stars,75,50+ bought in past month,419.99,basic variant price: nan,$499.99,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,https://m.media-amazon.com/images/I/71wTn+zoSr...,/Lorex-8-Channel-Security-Outdoor-Cameras/dp/B...,30-08-2025 19:56

# Analyzing column

In [23]:
df.shape

(42675, 16)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Title                     42675 non-null  object
 1   Rating                    41651 non-null  object
 2   Number_of_reviews         41651 non-null  object
 3   bought_in_last_month      39458 non-null  object
 4   Current/discounted_price  30926 non-null  object
 5   Price_on_variant          42675 non-null  object
 6   Listed_price              42675 non-null  object
 7   is_best_seller            42675 non-null  object
 8   is_sponsored              42675 non-null  object
 9   is_couponed               42675 non-null  object
 10  buy_box_availability      28022 non-null  object
 11  delivery_details          30955 non-null  object
 12  sustainability_badges     3408 non-null   object
 13  image_url                 42675 non-null  object
 14  product_url               40606 non-null  object
 15  collected_at              42675 non-null  object
dtypes: object(16)
memory usage: 5.2+ MB

In [25]:
df.describe()

,Title,Rating,Number_of_reviews,bought_in_last_month,Current/discounted_price,Price_on_variant,Listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at
count,42675,41651,41651,39458,30926,42675,42675,42675,42675,42675,28022,30955,3408,42675,40606,42675
unique,8808,31,4413,59,2576,3466,911,12,2,42,1,298,16,8038,40606,331
top,"Duracell Coppertop 9V Battery, 6 Count (Pack o...",4.6 out of 5 stars,25,100+ bought in past month,29.99,basic variant price: nan,No Discount,No Badge,Organic,No Coupon,Add to cart,"Delivery Mon, Sep 1",Small Business,https://m.media-amazon.com/images/I/51Xr76m2WL...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,27-08-2025 07:39
freq,744,6151,626,8801,825,21031,30364,40814,35664,40727,28022,6189,1341,1461,1,180

# Identifying Missing Values

In [26]:
df.isnull().sum()

Title                           0
Rating                       1024
Number_of_reviews            1024
bought_in_last_month         3217
Current/discounted_price    11749
Price_on_variant                0
Listed_price                    0
is_best_seller                  0
is_sponsored                    0
is_couponed                     0
buy_box_availability        14653
delivery_details            11720
sustainability_badges       39267
image_url                       0
product_url                  2069
collected_at                    0
dtype: int64

In [27]:
df["Rating"].value_counts(dropna = False).head(10)

Rating
4.6 out of 5 stars    6151
4.4 out of 5 stars    5525
4.5 out of 5 stars    5359
4.7 out of 5 stars    4664
4.8 out of 5 stars    4230
4.3 out of 5 stars    2927
4.2 out of 5 stars    2837
4.1 out of 5 stars    1959
4.0 out of 5 stars    1465
3.9 out of 5 stars    1316
Name: count, dtype: int64

In [28]:
df["bought_in_last_month"].value_counts(dropna=False).head(10)

bought_in_last_month
100+ bought in past month       8801
50+ bought in past month        5967
200+ bought in past month       5645
No featured offers available    4571
NaN                             3217
300+ bought in past month       2842
500+ bought in past month       2351
1K+ bought in past month        2084
400+ bought in past month       1436
20K+ bought in past month        772
Name: count, dtype: int64

In [29]:
df["Current/discounted_price"].value_counts(dropna=False).head(10)

Current/discounted_price
NaN       11749
29.99       825
119.99      695
13.99       585
24.99       502
49.99       478
59.99       474
49.95       471
25.47       461
85.99       441
Name: count, dtype: int64

In [30]:
df["sustainability_badges"].value_counts(dropna=False)#.head(10)

sustainability_badges
NaN                               39267
Small Business                     1341
Carbon impact                       769
Works with Alexa                    425
Energy efficiency                   262
Alexa Built-in                      184
Manufacturing practices             148
Energy efficiency +3 more           121
Energy efficiency +1 more            93
Safer chemicals +2 more              18
Forestry practices                   18
Recycled materials                    7
Recycled materials +2 more            7
Safer chemicals +1 more               6
Recycled materials +3 more            4
Made in Italy                         4
1 sustainability certification        1
Name: count, dtype: int64

In [31]:
df["buy_box_availability"].value_counts(dropna=False)#.head(10)

buy_box_availability
Add to cart    28022
NaN            14653
Name: count, dtype: int64

In [32]:
df[["Current/discounted_price", "Price_on_variant", "Listed_price"]].head(10)

  Current/discounted_price              Price_on_variant Listed_price
0                    89.68   basic variant price: 2.4GHz      $159.00
1                     9.99      basic variant price: nan       $15.99
2                      314      basic variant price: nan      $349.00
3                      NaN  basic variant price: $162.24  No Discount
4                      NaN   basic variant price: $72.74  No Discount
5                      NaN   basic variant price: $99.95  No Discount
6                      NaN   basic variant price: $88.11  No Discount
7                      NaN   basic variant price: $23.04  No Discount
8                    16.99      basic variant price: nan  No Discount
9                      NaN  basic variant price: $284.05  No Discount

# 1.Cleaning the price column

# Cleaning the price on variant column

In [33]:
df["variant_price_clean"] = (
    df["Price_on_variant"]
    .str.extract(r'\$(\d+(?:\.\d+)?)')[0]
    .astype(float)
)

In [34]:
df[["variant_price_clean","Price_on_variant"]].head(20)

    variant_price_clean              Price_on_variant
0                   NaN   basic variant price: 2.4GHz
1                   NaN      basic variant price: nan
2                   NaN      basic variant price: nan
3                162.24  basic variant price: $162.24
4                 72.74   basic variant price: $72.74
5                 99.95   basic variant price: $99.95
6                 88.11   basic variant price: $88.11
7                 23.04   basic variant price: $23.04
8                   NaN      basic variant price: nan
9                284.05  basic variant price: $284.05
10                  NaN      basic variant price: nan
11               880.95  basic variant price: $880.95
12                  NaN      basic variant price: nan
13                  NaN      basic variant price: nan
14                  NaN      basic variant price: nan
15                17.45   basic variant price: $17.45
16                38.86   basic variant price: $38.86
17                  NaN      basic variant price: nan
18                13.88   basic variant price: $13.88
19                33.51   basic variant price: $33.51

# Cleaning the listed price

In [35]:
df["Listed_price_clean"] = (
    df["Listed_price"]
    .str.extract(r'\$(\d+(?:\.\d+)?)')[0]
    .astype(float)
)

In [36]:
df["Listed_price_clean"]

0        159.00
1         15.99
2        349.00
3           NaN
4           NaN
          ...
42670       NaN
42671       NaN
42672      1.00
42673     15.98
42674    499.99
Name: Listed_price_clean, Length: 42675, dtype: float64

In [37]:
df[["Current/discounted_price","variant_price_clean","Listed_price_clean"]].head(25)

   Current/discounted_price  variant_price_clean  Listed_price_clean
0                     89.68                  NaN              159.00
1                      9.99                  NaN               15.99
2                       314                  NaN              349.00
3                       NaN               162.24                 NaN
4                       NaN                72.74                 NaN
5                       NaN                99.95                 NaN
6                       NaN                88.11                 NaN
7                       NaN                23.04                 NaN
8                     16.99                  NaN                 NaN
9                       NaN               284.05                 NaN
10                    14.99                  NaN                 NaN
11                      NaN               880.95                 NaN
12                    29.99                  NaN                 NaN
13                   249.99                  NaN                 NaN
14                    69.95                  NaN                 NaN
15                      NaN                17.45                 NaN
16                    39.97                38.86                 NaN
17                    14.49                  NaN                 NaN
18                    16.98                13.88                 NaN
19                      NaN                33.51                 NaN
20                    16.95                16.78               19.98
21                      NaN               146.14                 NaN
22                     9.89                 8.87               14.33
23                      NaN                16.10                 NaN
24                      NaN                  NaN                 NaN

In [38]:
df["final_price"] = (
    df["Current/discounted_price"]
    .fillna(df["variant_price_clean"])
    .fillna(df["Listed_price_clean"])
)

In [39]:
df["final_price"].head(25)

0      89.68
1       9.99
2        314
3     162.24
4      72.74
5      99.95
6      88.11
7      23.04
8      16.99
9     284.05
10     14.99
11    880.95
12     29.99
13    249.99
14     69.95
15     17.45
16     39.97
17     14.49
18     16.98
19     33.51
20     16.95
21    146.14
22      9.89
23      16.1
24       NaN
Name: final_price, dtype: object

In [40]:
df['final_price'] = pd.to_numeric(df['final_price'], errors='coerce')

In [41]:
df[["Current/discounted_price","variant_price_clean","Listed_price_clean","final_price"]].head(25)

,Current/discounted_price,variant_price_clean,Listed_price_clean,final_price
0,89.68,NaN,159.00,89.68
1,9.99,NaN,15.99,9.99
2,314,NaN,349.00,314.00
3,NaN,162.24,NaN,162.24
4,NaN,72.74,NaN,72.74
5,NaN,99.95,NaN,99.95
6,NaN,88.11,NaN,88.11
7,NaN,23.04,NaN,23.04
8,16.99,NaN,NaN,16.99
9,NaN,284.05,NaN,284.05
10,14.99,NaN,NaN,14.99
11,NaN,880.95,NaN,880.95
12,29.99,NaN,NaN,29.99
13,249.99,NaN,NaN,249.99
14,69.95,NaN,NaN,69.95
15,NaN,17.45,NaN,17.45
16,39.97,38.86,NaN,39.97
17,14.49,NaN,NaN,14.49
18,16.98,13.88,NaN,16.98
19,NaN,33.51,NaN,33.51
20,16.95,16.78,19.98,16.95
21,NaN,146.14,NaN,146.14
22,9.89,8.87,14.33,9.89
23,NaN,16.10,NaN,16.10
24,NaN,NaN,NaN,NaN

# 2.Clean Rating column

In [42]:
df["Rating_clean"] =(
    df["Rating"]
    .str.extract(r'(\d\.\d)')
    .astype(float)
)

In [43]:
df["Rating_clean"]

0        4.6
1        4.3
2        4.6
3        4.6
4        4.8
        ...
42670    5.0
42671    4.2
42672    4.3
42673    4.7
42674    4.4
Name: Rating_clean, Length: 42675, dtype: float64

# 3.Clean the number of review column

In [44]:
df["Number_of_reviews_clean"] = (
    df["Number_of_reviews"]
    .str.replace(",","",regex = False)
    .astype("Int64")
)

In [45]:
df[["Number_of_reviews", "Number_of_reviews_clean"]].head(10)

  Number_of_reviews  Number_of_reviews_clean
0               375                      375
1             2,457                     2457
2             3,044                     3044
3            35,882                    35882
4            28,988                    28988
5            44,522                    44522
6            13,466                    13466
7            38,105                    38105
8             4,380                     4380
9             7,308                     7308

# 4.Clean the bought in last month column

In [46]:
df[['bought_in_last_month']].value_counts().head(30)

bought_in_last_month
100+ bought in past month                                                                                                                                                       8801
50+ bought in past month                                                                                                                                                        5967
200+ bought in past month                                                                                                                                                       5645
No featured offers available                                                                                                                                                    4571
300+ bought in past month                                                                                                                                                       2842
500+ bought in past month                                                                                                                                                       2351
1K+ bought in past month                                                                                                                                                        2084
400+ bought in past month                                                                                                                                                       1436
20K+ bought in past month                                                                                                                                                        772
More Buying Choices                                                                                                                                                              654
Typical:                                                                                                                                                                         532
List:                                                                                                                                                                            518
List Price:                                                                                                                                                                      511
2K+ bought in past month                                                                                                                                                         426
800+ bought in past month                                                                                                                                                        280
Shop products from small business brands sold in Amazon’s store. Discover more about the small businesses partnering with Amazon and Amazon’s commitment to empowering them.     262
3K+ bought in past month                                                                                                                                                         249
600+ bought in past month                                                                                                                                                        229
10K+ bought in past month                                                                                                                                                        229
4K+ bought in past month                                                                                                                                                         196
5K+ bought in past month                                                                                                                                                         120
ESRB Rating: Everyone                                                                                                                                                            107
700+ bought in past month                                                                                                                                                        102
90K+ bought in past month                                                                                                                                                         92
6K+ bought in past month                                                                                                                                                          81
900+ bought in past month                                                                                                                                                         63
7K+ bought in past month                                                                                                                                                          49
This product is certified by Amazon to work with Alexa. This product can be controlled with your voice through Alexa-enabled devices such as Amazon Echo and Amazon Tap.          47
9K+ bought in past month                                                                                                                                                          44
8K+ bought in past month                                                                                                                                                          36
Name: count, dtype: int64

In [47]:
import re
import numpy as np

def clean_bought(value):
    if pd.isna(value):
        return np.nan
    
    value = str(value).strip()
    
    match = re.search(r'([\d,.]+)\s*([Kk]?)\+', value)
    
    if not match:
        return np.nan
    
    number = float(match.group(1).replace(',', ''))
    suffix = match.group(2).upper()
    
    if suffix == 'K':
        number *= 1000
    
    return number

df['bought_in_last_month_clean'] = df['bought_in_last_month'].apply(clean_bought)

In [48]:
df['bought_in_last_month_clean']

0          300.0
1         6000.0
2         2000.0
3        10000.0
4        10000.0
          ...
42670      100.0
42671      200.0
42672       50.0
42673      500.0
42674       50.0
Name: bought_in_last_month_clean, Length: 42675, dtype: float64

In [49]:
df[['bought_in_last_month', 'bought_in_last_month_clean']].head(20)

          bought_in_last_month  bought_in_last_month_clean
0    300+ bought in past month                       300.0
1     6K+ bought in past month                      6000.0
2     2K+ bought in past month                      2000.0
3    10K+ bought in past month                     10000.0
4    10K+ bought in past month                     10000.0
5   100K+ bought in past month                    100000.0
6    10K+ bought in past month                     10000.0
7    10K+ bought in past month                     10000.0
8                          NaN                         NaN
9    10K+ bought in past month                     10000.0
10  100K+ bought in past month                    100000.0
11   10K+ bought in past month                     10000.0
12   100+ bought in past month                       100.0
13    1K+ bought in past month                      1000.0
14   500+ bought in past month                       500.0
15  100K+ bought in past month                    100000.0
16   80K+ bought in past month                     80000.0
17  100K+ bought in past month                    100000.0
18  100K+ bought in past month                    100000.0
19   10K+ bought in past month                     10000.0

In [50]:
df['bought_in_last_month_clean'].value_counts(dropna=False).head(20)

bought_in_last_month_clean
NaN        10510
100.0       8801
50.0        5967
200.0       5645
300.0       2842
500.0       2351
1000.0      2084
400.0       1436
20000.0      772
2000.0       426
800.0        280
3000.0       249
600.0        229
10000.0      229
4000.0       196
5000.0       120
700.0        102
90000.0       92
6000.0        81
900.0         63
Name: count, dtype: int64

In [51]:
df.columns.tolist()

['Title',
 'Rating',
 'Number_of_reviews',
 'bought_in_last_month',
 'Current/discounted_price',
 'Price_on_variant',
 'Listed_price',
 'is_best_seller',
 'is_sponsored',
 'is_couponed',
 'buy_box_availability',
 'delivery_details',
 'sustainability_badges',
 'image_url',
 'product_url',
 'collected_at',
 'variant_price_clean',
 'Listed_price_clean',
 'final_price',
 'Rating_clean',
 'Number_of_reviews_clean',
 'bought_in_last_month_clean']

In [52]:
df.shape

(42675, 22)

# Removing the duplicates

In [53]:
df["Title"].duplicated().sum()

np.int64(33867)

In [54]:
df.duplicated().sum()

np.int64(962)

In [55]:
df = df.drop_duplicates()

In [56]:
df.duplicated().sum()

np.int64(0)

In [57]:
df

,Title,Rating,Number_of_reviews,bought_in_last_month,Current/discounted_price,Price_on_variant,Listed_price,is_best_seller,is_sponsored,is_couponed,...,sustainability_badges,image_url,product_url,collected_at,variant_price_clean,Listed_price_clean,final_price,Rating_clean,Number_of_reviews_clean,bought_in_last_month_clean
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6 out of 5 stars,375,300+ bought in past month,89.68,basic variant price: 2.4GHz,$159.00,No Badge,Sponsored,Save 15% with coupon,...,Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,21-08-2025 11:14,NaN,159.00,89.68,4.6,375,300.0
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3 out of 5 stars,"2,457",6K+ bought in past month,9.99,basic variant price: nan,$15.99,No Badge,Sponsored,No Coupon,...,NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,21-08-2025 11:14,NaN,15.99,9.99,4.3,2457,6000.0
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6 out of 5 stars,"3,044",2K+ bought in past month,314,basic variant price: nan,$349.00,No Badge,Sponsored,No Coupon,...,NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,21-08-2025 11:14,NaN,349.00,314.00,4.6,3044,2000.0
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6 out of 5 stars,"35,882",10K+ bought in past month,NaN,basic variant price: $162.24,No Discount,Best Seller,Organic,No Coupon,...,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,/Apple-Cancellation-Transparency-Personalized-...,21-08-2025 11:14,162.24,NaN,162.24,4.6,35882,10000.0
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8 out of 5 stars,"28,988",10K+ bought in past month,NaN,basic variant price: $72.74,No Discount,No Badge,Organic,No Coupon,...,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,/Apple-MX542LL-A-AirTag-Pack/dp/B0D54JZTHY/ref...,21-08-2025 11:14,72.74,NaN,72.74,4.8,28988,10000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42670,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0 out of 5 stars,1,100+ bought in past month,195.99,basic variant price: nan,No Discount,No Badge,Organic,No Coupon,...,NaN,https://m.media-amazon.com/images/I/51KCB+egEs...,/Elgato-4K-Pro-Internal-Capture/dp/B0DLR3WQWR/...,30-08-2025 19:56,NaN,NaN,195.99,5.0,1,100.0
42671,"Arlo Essential Spotlight Camera, Wireless Secu...",4.2 out of 5 stars,20,200+ bought in past month,89.99,basic variant price: $25.00 off coupon applied,No Discount,No Badge,Organic,Save $25.00 with coupon,...,NaN,https://m.media-amazon.com/images/I/51jV+o1LZE...,/Arlo-Essential-Spotlight-Camera-Surveillance/...,30-08-2025 19:56,25.00,NaN,89.99,4.2,20,200.0
42672,"GIGABYTE - AORUS FO32U2-32"" QD OLED Gaming Mon...",4.3 out of 5 stars,57,50+ bought in past month,899.99,basic variant price: Lowest price in 30 days,"$1,099.99",Save 18%,Organic,No Coupon,...,NaN,https://m.media-amazon.com/images/I/71ySPkNLkG...,/GIGABYTE-FO32U2-32-3840x2160-240Hz-FreeSync-A...,30-08-2025 19:56,NaN,1.00,899.99,4.3,57,50.0
42673,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7 out of 5 stars,"7,102",500+ bought in past month,10.39,basic variant price: nan,$15.98,No Badge,Organic,No Coupon,...,NaN,https://m.media-amazon.com/images/I/411c0JFJ79...,/Monoprice-XLR-Male-4-Inch-Cable/dp/B001UJEKZ6...,30-08-2025 19:56,NaN,15.98,10.39,4.7,7102,500.0
42674,Lorex Fusion 1080p HD Security Camera System w...,4.4 out of 5 stars,75,50+ bought in past month,419.99,basic variant price: nan,$499.99,No Badge,Organic,No Coupon,...,NaN,https://m.media-amazon.com/images/I/71wTn+zoSr...,/Lorex-8-Channel-Security-Outdoor-Cameras/dp/B...,30-08-2025 19:56,NaN,499.99,419.99,4.4,75,50.0

In [58]:
df.to_csv("amazon_cleaned.csv", index=False)